import React, { useEffect, useState } from 'react'
import { Card, FormField, Loader } from '../components'

const Home = () => {
    const [loading, setLoading] = useState(false)
    const [allPosts, setAllPosts] = useState(null)
    const [searchText, setSearchText] = useState('')
    const [searchedResult, setSearchedResult] = useState(null)
    const [searchTimeout, setSearchTimeout] = useState(null)

    useEffect(() => {
        const fetchPosts = async () => {
            setLoading(true)

            try {
                // const response = await fetch('http://localhost:8000/api/v1/post', {
                const response = await fetch('http://192.168.1.3:8000/api/v1/post', {
                    method: 'GET',
                    headers: {
                        'Content-Type': 'application/json',
                    }
                })

                if (response.ok) {
                    const result = await response.json()
                    setAllPosts(result.data.reverse())
                }
            } catch (err) {
                alert(error)
            } finally {
                setLoading(false)
            }

        }
        fetchPosts()

    }, [])


    const RenderCards = ({ data, title }) => {
        if (data?.length > 0)
            return data.map((post) =>
                <Card
                    key={post._id}
                    {...post}
                />)
        return <h2 className='mt-5 font-bold text-[#6369ff] text-xl uppercase'>{title}</h2>
    }

    const handleSearchChange = (e) => {
        clearTimeout(searchTimeout)

        setSearchText(e.target.value)

        setSearchTimeout(
            setTimeout(() => {
            const searchResult = allPosts.filter((post) =>
                post.name.toLowerCase().includes(searchText.toLowerCase()) || 
                post.prompt.toLowerCase().includes(searchText.toLowerCase())
            
            )

            setSearchedResult(searchResult)
        }, 300)
        )
    }

    return (
        <section className='max-w-7xl mx-auto'>
            <div>
                <h1 className='font-extrabold text-[#222328] text-[2em]'>
                    The Community Showcase
                </h1>

                <p className='mt-2 text-[#666e75] max-w-[500px] leading-5'>
                    Browse through a collection of imaginative and visually stunning images generated by DALL-E AI.
                </p>

                <div className='mt-16'>
                    <FormField 
                        labelName="Search posts"
                        type="text"
                        name="text"
                        placeholder="Search posts"
                        value={searchText}
                        handleChange={handleSearchChange}
                    />
                </div>

                <div className='mt-10'>
                    {loading ? (
                        <div className='flex justify-center items-center'>
                            <Loader />
                        </div>
                    ) : (
                        <>
                            {searchText && (
                                <h2 className='font-medium text-[#666e75] text-xl mb-3'>
                                    Showing results for <span className='text-[#222328]'>{searchText}</span>
                                </h2>
                            )}
                            <div className='grid grid-cols-1 lg:grid-cols-4 sm:grid-cold-3 xs:grid-cols-2 gap-4'>
                                {searchText ? (
                                    <RenderCards
                                        data={searchedResult}
                                        title="No search results found."
                                    />
                                ) : (
                                    <RenderCards
                                        data={allPosts}
                                        title="No posts found."
                                    />
                                )}
                            </div>
                        </>
                    )}
                </div>
            </div>
        </section>
    )
}

export default Home